version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
  - package-ecosystem: "docker"
    directory: "/laravel"
    schedule:
      interval: daily
      time: "04:00"
  - package-ecosystem: "composer"
    directory: "/laravel"
    schedule:
      interval: daily
      time: "04:00"
  - package-ecosystem: "npm"
    directory: "/laravel"
    schedule:
      interval: daily
      time: "04:00"
